### ISSUE TITLE
Enabling debug serial UART on Radxa 3E

### ISSUE THREAD

**Issue by defencedog** [platima/sbc-images#1]
I am trying to enable serial debug UART as mentioned here https://wiki.radxa.com/File:Usb2ttl-cable-definition.jpeg
For this to enable I need to enable / interact with `UART2_TX_M0` `UART2_RX_M0` as mentioned in [GPIO pin layout](https://docs.radxa.com/en/zero/zero3/hardware-design/hardware-interface) 

By default it didn't work so I even compiled & added overlays using `sudo armbian-add-overlay rk3568-uart2-m0.dts` as mentioned here 
```
https://github.com/radxa-pkg/radxa-overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-uart2-m0.dts
```
no success!

```
OS: Armbian (24.8.4) aarch64 
Host: Radxa ZERO 3 
Kernel: 6.1.75-vendor-rk35xx 
Uptime: 22 mins 
Packages: 888 (dpkg) 
Shell: bash 5.1.16 
Terminal: ttyd 
CPU: (4) @ 1.800GHz 
Memory: 480MiB / 3732MiB 
```

**Comment by platima** [comment]
UART worked when I tested it on the images I made in this repo.

They are out of date now though, you should build your own using Radxa Build.

If you build your own Armbian image, UART should also work by default.

The overlay should not be required, but it was worth trying.

If UART does not work by default or with UART, then you most likely have not connected it to your computer correctly.

As mentioned to you on Reddit, you need to ensure you're using a correct UART to serial adapter, with the right baud, flow control and stop bit.

Good luck.

**Comment by defencedog** [comment]
Thanks for your kind reply
